---
title: "<b>Portugal Market Analysis</b>"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    orientation: columns
    vertical_layout: fill
    theme: simplex
editor_options: 
  chunk_output_type: console
runtime: shiny
---
<!-- theme alternatives: "cerulean",  "journal", "readable", "simplex", "united", "yeti" -->

```{r SETUP, message=FALSE, include=FALSE}
#GENERAL CODE CHUNK SETUP
knitr::opts_chunk$set(echo = FALSE, message=FALSE)

#+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-#
#PACKAGE INSTALLATION AND LOADING
#-the essential packages required to load the document are markdown, knitr, flexdashboard and pacman.
#-the following code checks for their installation, installing them if required, and proceeds
#-to install/load other necessary packages.

if(!require("markdown")) install.packages("markdown")
if(!require("knitr")) install.packages("knitr")
if(!require("flexdashboard")) install.packages("flexdashboard")
if(!require("pacman")) install.packages("pacman") 
#--pacman function essential for loading and installing (if not already installed) packages together

pacman::p_load(
  knitr,           #--essential for rmarkdown document modification
  tidyverse,       #--contains ggplot2, readr, tibble, dplyr, magrittr
  reactable,       #--for creation of large tables
  janitor,         #--manipulation, summarisation of messy data, plus duplicate detection
  inspectdf,       #--dataframe inspection, relative to value (used in dataset analysis)
  highcharter,     #--interactive data visualisation
  htmltools,       #--website page options (zoom, scrolling)
  collapsibleTree, #--for happiness factor collapsible tree
  broom,           #--needed to convert linear model for interpolation line into dataframe
  dygraphs,        #--package for time series model creation
  xts,             #--data format required by dygraphs
  shiny            #--"runtime: shiny" in JMAL header already loads the library, useful for debugging w/o knitting
)
```


```{r FUNCTIONS & DATA IMPORTING, message=FALSE, include=FALSE}
#FUNCTIONS
#-".csv" extension remover, for variable list
csv_remove <- 
  function(x){
    substr(x, 1, nchar(x)-4)
  }

#-----#

#-Highcharter() scatterplot format
scplot_custom <- function(x){ 
  x %>% 
    hc_title(style=list(
               fontWeight="bold",
               fontSize= "15px",
               fontFamily= "Lato"
              )
             ) %>% 
    hc_size(., width=80, height=310) %>% 
    hc_tooltip(., 
       headerFormat = "",
       pointFormat = 
         "<b>{point.name}</b><br>X: {point.x:.1f}%<br>Y: {point.y:.2f}") %>% 
    hc_yAxis(
      type="linear",
      lineWidth=5,
      labels=list(format="{value}/10"),
      lineColor="#ecf0f1") %>% 
    hc_xAxis(
      type="linear",
      lineWidth=5,
      labels=list(format="{value}%"), 
      lineColor="#ecf0f1") %>% 
    hc_plotOptions(., scatter=list(color="#18bc9c"))
  }

#+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-#

#DATA IMPORTING
dsets <- list.files(path="./Datasets", pattern = "*.csv", full.names = FALSE)   #vector with file names

dsets <-
  #assign the value contained in each dataset to its respective name
  setNames(
    lapply(list.files(path= "./Datasets", pattern="*.csv", full.names = TRUE), read.csv), 
    #reading each csv file, same code as dsets w/ exception that it takes full file path rather than just the name
    lapply(dsets, csv_remove)
    #removing ".csv" file extension to create variable list, function above
  )

#final dsets vector contains variables associated w/ respective dataset:
#-global edits done to reduce variable names, since discarded data not required.
#-method flexible to increases, decreases or variations in order to dataset directory.
```

<!-- INTRODUCTION PAGE -->

# **Introduction**

## Definitions and Graph {data-width="390" data-height="800"}

### **Definitions**
Definitions:
-Snack Market
-Portugal
-Cristiano Ronaldo effect


### **Index**
filler
```{r}
4+4
```

## **Possible Graph** {data-width="610"}
filler filler filler
-filler
-filler

```{r}
5+6
```


